version: '3.3'

services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  super:
    &super
    image: loyaltycorp/manage-app
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules/node-sass
  payments:
    << : *super
    depends_on: [ super ]
    environment:
      - YARN_DEV_NAME=payments
      - VUE_APP_BASE_URL=/payments
  online-offers:
    << : *super
    depends_on: [ super ]
    environment:
      - YARN_DEV_NAME=online-offers
      - VUE_APP_BASE_URL=/online-offers
  nginx:
    depends_on: [ super ] # apps should be ready on 8080 port before server launch
    image: loyaltycorp/manage-nginx
    build:
      context: ./
      dockerfile: .docker/nginx.dockerfile
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - '8080:8080'
    environment:
      WAIT_HOSTS: super:8080, online-offers:8080, payments:8080
      WAIT_HOSTS_TIMEOUT: 150
      WAIT_SLEEP_INTERVAL: 3
