version: '3'

services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  super:
    image: manage_admin:latest
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: bash -c "yarn link node-sass && yarn dev super"
  payments:
    depends_on: [ super ]
    image: manage_admin:latest
    working_dir: /home/node/app
    environment:
      - VUE_APP_BASE_URI=/payments
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: bash -c "yarn link node-sass && yarn dev payments"
  nginx:
    depends_on: [ dockerhost ] # apps should be ready on 8080 port before server launch
    image: manage_nginx:latest
    build:
      context: ./
      dockerfile: .docker/nginx.dockerfile
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - '8080:8080'
    environment:
      WAIT_HOSTS: super:8080, payments:8080
      WAIT_HOSTS_TIMEOUT: 150
      WAIT_SLEEP_INTERVAL: 3
    command: /bin/bash -c "/wait && exec nginx -g 'daemon off;'"
