version: '3'

services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  nginx:
    depends_on: [ dockerhost ]
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - '8080:8080'